### ISSUE TITLE
Use blocking insert statements when creating execution records

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#101]
We are currently using a non-blocking update when creating execution records. This is potentially problematic as the migrator uses the returned projection to determine if another executor is already running the job. @bserdar has indicated that we should be using an insert with is blocking, eliminating the risk of duplicated work being performed.

**Comment by jewzaam** [comment]
Is this a nuance to how we do updates to arrays?  Because we're not creating a new document in a collection, so I'm wondering how we can use an insert.  Other than by splitting out jobExecution to a new entity.

**Comment by bserdar** [comment]
This is because we're implementing updates as read-update-writes.

jobExecution doesn't have to be a new entity, but a locking scheme needs to
be applied so that only one node can update a job. So, a new entity is
required, could be something like a jobLock that only keeps if a job is
locked or not, and when. The only way to update a job to insert a new
element to the array would be to lock it first.

This needs further elaboration to keep track of stale locks.

**Comment by dcrissman** [comment]
Would a JMS be a better solution?

**Comment by bserdar** [comment]
How?

It might overcomplicate things. It doesn't address the real problem of
synchronization, only shifts it to a different domain.

**Comment by dcrissman** [comment]
I don't pretend to be a JMS expert, but I a little experience and have read it supports transactions. My thinking is instead of a migrator fetching all possible jobs when it initializes and then having to check each job before it actually runs to make sure it is not being or been processed, maybe it just grabs the next job from queue, processes it, and pops it off the queue. Let the queue decide when a message's transaction times out and re-add it to the pool.

I have worked a little with JMS, but not specifically with transations. So I don't know the level of effort this would add. Mostly throwing it out as an idea.

**Comment by bserdar** [comment]
In my opinion, it is much easier to implement a locking scheme. JMS will
bring a lot more complexity. How will you persist the messages? You'll need
a new DB there. Once you add a new DB, why don't you simply use it
directly? That said, why not store migration jobs in Oracle? It supports
transactions too.

**Comment by luan-cestari** [comment]
As @bserdar said, I also think it might eb easier to use Oracle (as we don't add another system into the migration which will need some work for the integration and new bugs). I think we had a similar discussion on mojo about transactions and some alternatives. One of them (not sure if it is in mojo document but I read this on some posts on the internet) would create another collection to manage the transaction

**Comment by dcrissman** [comment]
@bserdar Can this issue be closed out now that you implemented the locking mechanism?

**Comment by bserdar** [comment]
No longer an issue.
