### ISSUE TITLE
Add indexes for migrationJob entity

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#108]
Queries are doing full scans right now.  Recommend indexes on:
* whenAvailableDate
* jobExecutions.completedFlag

**Comment by jewzaam** [comment]
Pending #97 as field "jobExecutions.completedFlag" will be replaced.

**Comment by dcrissman** [comment]
The above two changes are made in different branches so that we could pull the first one in by itself if desired.
