### ISSUE TITLE
During migration, there needs to be a way to assign a value to a destination field that may not exist in the source

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#112]
During the migration process there needs to be a way to populate fields that exist in the destination entity, but that do not exist in the source entity (eg. migration_date, migrated_by).

**Comment by dcrissman** [comment]
@jewzaam and I were discussing possibly adding a plugin capability to the migrator that could define what fields to auto-populate, under what conditions, and what the auto-populated value should be.

**Comment by jewzaam** [comment]
A concern is that these things are specific to an organization's metadata and maybe specific to an entity.  Hence the plugin capability to allow modifying the functionality.

**Comment by jewzaam** [comment]
In discussions it would make sense to happen just before writing to the destination.  This implies after data comparisons are done.  There's no need to do this work if nothing is being written to the destination.  Auto populated fields maybe should be excluded from comparison.  It could be handled automatically, not sure we want to force it to be excluded.

**Comment by dcrissman** [comment]
Possibly related too https://github.com/lightblue-platform/lightblue-core/issues/152

**Comment by paterczm** [comment]
Can this be closed?
