### ISSUE TITLE
Reminder: Add migrationDate and migratedFrom to entities

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#143]
* add to the entities we're migrating
* make part of standard for migrated entities
* update migration internally to support populating these fields

Why?  Data on when entities were migrated and from where is useful and should be separate from other fields.

**Comment by dcrissman** [comment]
@jewzaam changes made and pushed up

**Comment by jewzaam** [comment]
@dcrissman changed how properties are loaded to only synchronize if required
