### ISSUE TITLE
Bug on one unit test from MigrationJobTest using mutithread

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-migrator#154]
After merged some PRs (for example the PR related to log4j bridge), we found a failure (it only occurred on the build using java 1.8 but it seems that may also happen with 1.7). The error occurred in one of the unit tests, to be more precisely it was com.redhat.lightblue.migrator.consistency.MigrationJobTest.testException_getSourceDocuments_execute(MigrationJobTest.java:1030) (the build job that failed was https://travis-ci.org/lightblue-platform/lightblue-migrator/jobs/57338079 but after the next build it lost the message ). The problem lead to this assert https://github.com/lightblue-platform/lightblue-migrator/blob/master/consistency-checker/src/test/java/com/redhat/lightblue/migrator/consistency/MigrationJobTest.java#L1030

That assertion is kind of too "optimistic" and we should change it, the current thread that is processing the tests could have the bad luck to not have any processing in cpu for awhile which could be enough time to make those 2 threads be able to process more jobs that that line statement expects 

 We might want to make a more safe assert there creates a blocking during the processing or change that so this problem does not occur again

**Comment by dcrissman** [comment]
See #164 for some additional details.

**Comment by jewzaam** [comment]
Blocking some of the threads to force the condition sounds like a good idea.
