### ISSUE TITLE
Report issue on infinite dead job executions

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-migrator#166]
For some reason we're in a state right now that all job executions get blocked.  A cron job restarts migrator every 3 hours (to cleanup any dead connections.. known issue being fixed soon).  Each of those blocked executions is then marked dead and retried, because of sorting.  And we're in a state that the oldest 50 jobs have been retried ever 3 hours for 3 days now, 26 dead executions.  Nothing is reported as an error. 

We should have a threshold for when we decide that there are too many executions and to log an error and do something.  What should that something be?  Ideally it should trigger an alert.  Configure an email address that could be notified for issues like this?

**Comment by dcrissman** [comment]
If I understand you correctly, then once a job gets put into a COMPLETED_DEAD state, it is never able to finish after that... is that correct?

I see a bunch of ABORTED_UNKNOWN states after a COMPLETED_DEAD, is that what you are looking at also?

**Comment by jewzaam** [comment]
Executions in state of COMPLETED_DEAD just mean the execution wasn't able to complete.  Migrator picks up that job again and attempts to execute it again.  The problem is that the conditions that caused the execution to no process are not cleared, meaning it becomes dead again.  And processed again... over and over.

1. migrator picks job A with no executions
2. migrator is blocked when trying to execute job
3. migrator is restarted
4. migrator picks job A that was executing too long
5. job A is marked as dead
6. goto step 2

**Comment by bserdar** [comment]
No longer relevant.
