### ISSUE TITLE
Having a Proxy Facade Factory would make migration & testing efforts easier

### ISSUE THREAD

**Issue by jblashka** [lightblue-platform/lightblue-migrator#171]
Currently during migration we have to write a DAOFacadeImpl for each and every DAO, but the contents of each method is basically the same:
return callDAOXMethod(ReturnType[].class, "MethodName", new Class[]{ArgumentType.class}, Argument);

Instead, we can create a proxy factory that takes in the two implementations and takes care of all the grunt work of writing all these methods. We can add annotations (@Read, @Write, @SourceOnly, etc.) to the DAO interface that the proxy's interceptor can utilize when methods are called to determine how to handle the method calls. This would be a new class utilizing the existing DAOFacadeBase in case we still need to have some exceptions in how the method calls are handled we'll still have the old process to fall back on.

This also lightens the testing effort because there's no longer many FacadeDAOImpl classes to test, just the proxy factory.

**Comment by paterczm** [comment]
+1

The annotations we need are: Read,Insert, Update and SourceOnly.

**Comment by dcrissman** [comment]
I would argue that we still want to test the api endpoints against a lightblue backend and traditional backend to ensure the same results.
