### ISSUE TITLE
Store feature flags in database

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-migrator#174]
If things go wrong, we need a way to quickly reduce the amount of lightblue traffic or even disable it completely. Running puppet on each services node is neither quick nor convenient. Use JDBCStateRepository (see http://www.togglz.org/documentation/repositories.html) to store the flags.

**Comment by jewzaam** [comment]
Is the state of a flag cached?  If so, how often is the cache refreshed?  If not, is that a requirement?

**Comment by jewzaam** [comment]
We talked somewhere about this being able to do separate set of flags using different tables.  So if we need flags for thing A and B that are co-located then we create those flags in two tables.

**Comment by paterczm** [comment]
> Is the state of a flag cached? If so, how often is the cache refreshed? If not, is that a requirement?

Yes, I believe it is a requirement. CachingStateRepository can be used together with JDBCStateRepository. We just need to decide on expiration timeout - I propose 3 minutes.

**Comment by paterczm** [comment]
Agreed, one table per service which is controlled by feature flags.
