### ISSUE TITLE
Doesn't build + tests fail

### ISSUE THREAD

**Issue by jblashka** [lightblue-platform/lightblue-migrator#175]
There are compilation issues in ConsistencyCheckerTest.java and when I fix those I see some tests failing in ITCaseConsistencyCheckerTest:

testGetNextAvailableJob(com.redhat.lightblue.migrator.consistency.ITCaseConsistencyCheckerTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoSuchMethodError: com.redhat.lightblue.client.http.LightblueHttpClient.data(Lcom/redhat/lightblue/client/request/LightblueRequest;)Lcom/redhat/lightblue/client/response/LightblueResponse;

Possibly some pom/versioning issue when some other artifact got updated?

**Comment by jblashka** [comment]
It looks like PR #173 is supposed to partially address this

**Comment by dcrissman** [comment]
It is some sort of runtime issue where it seems to be grabbing a wrong/bad dependency somehow. I was able to reproduce locally by blowing away my local repo and pulling dependencies down from scratch. I am attempting to rebuild dependencies in travis now.

**Comment by dcrissman** [comment]
As soon as https://github.com/lightblue-platform/lightblue-migrator/pull/173 is merged, the issues you are having should go away. You may have to blow away part of your local maven repository.

Something like  rm -rf ~/.m2/repository/com/redhat/lightblue/

**Comment by jblashka** [comment]
Looks like it's all better now. I didn't have to remove any of the local maven repo, just building with -U did the job.
