### ISSUE TITLE
Migrator logs lack timestamp

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-migrator#216]
Timestamp will help investigating inconsistency errors.

**Comment by paterczm** [comment]
@BVulaj, perhaps this is something you could take?

**Comment by BVulaj** [comment]
When ran locally, the migrator has timestamps on logs as expected after adding the necessay slf4j-log4j implementation.  I'm waiting on access to the COS dev environments in order to check the actual deployment

**Comment by bserdar** [comment]
The logfile for the deploed migrator is in the internal migrator project,
not in the lightblue-migrator project.

The best way to solve this would be to have the logfile outside the package.
