### ISSUE TITLE
callDAO*Method throws Throwable?

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-migrator#251]
In

```java
            } catch (InvocationTargetException e) {
                throw e.getCause();
```

It would be nice to check if the cause is an Exception and throw that, otherwise throw Error ie

```java
            Throwable cause = e.getCause();

            if (cause instanceof Error) {
                throw (Error) cause;
            }

            throw cause;
```

This would prevent having to do this in clients... currently I feel like I should do this to prevent wrapping an Error in a RuntimeException :/

**Comment by paterczm** [comment]
https://github.com/lightblue-platform/lightblue-migrator/pull/236
