### ISSUE TITLE
Request based gradual rollout strategy percentage does not match reality

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-migrator#253]
This is because gradual rollout strategy we use is actually user based (see [GradualActivationStrategy](https://github.com/togglz/togglz/blob/master/core/src/main/java/org/togglz/core/activation/GradualActivationStrategy.java)), we just trick it by generating a new username (from 0 to 100) for each request. The resulting distribution is quite far from expected, probably because of small set of values generated (0 - 100). To fix this, we could write our own activation strategy.

Here are the mappings from set percentage to resulting percentage:
```
<percentage set> -> <resulting percentage>  
0 -> 0  
1 -> 1  
2 -> 2  
3 -> 3  
4 -> 4  
5 -> 6  
6 -> 7  
7 -> 8  
8 -> 10  
9 -> 11  
10 -> 12  
11 -> 13  
12 -> 14  
13 -> 15  
14 -> 17  
15 -> 19  
16 -> 21  
17 -> 22  
18 -> 24  
19 -> 25  
20 -> 26  
21 -> 28  
22 -> 30  
23 -> 32  
24 -> 34  
25 -> 36  
26 -> 37  
27 -> 38  
28 -> 39  
29 -> 41  
30 -> 43  
31 -> 45  
32 -> 46  
33 -> 47  
34 -> 49  
35 -> 50  
36 -> 52  
37 -> 54  
38 -> 55  
39 -> 56  
40 -> 57  
41 -> 59  
42 -> 60  
43 -> 62  
44 -> 63  
45 -> 64  
46 -> 65  
47 -> 66  
48 -> 66  
49 -> 67  
50 -> 70  
51 -> 71  
52 -> 72  
53 -> 73  
54 -> 73  
55 -> 73  
56 -> 74  
57 -> 74  
58 -> 74  
59 -> 75  
60 -> 77  
61 -> 77  
62 -> 77  
63 -> 78  
64 -> 78  
65 -> 79  
66 -> 80  
67 -> 80  
68 -> 80  
69 -> 80  
70 -> 82  
71 -> 82  
72 -> 82  
73 -> 82  
74 -> 82  
75 -> 84  
76 -> 84  
77 -> 85  
78 -> 85  
79 -> 85  
80 -> 86  
81 -> 86  
82 -> 87  
83 -> 87  
84 -> 87  
85 -> 89  
86 -> 89  
87 -> 89  
88 -> 89  
89 -> 90  
90 -> 91  
91 -> 92  
92 -> 93  
93 -> 94  
94 -> 95  
95 -> 97  
96 -> 98  
97 -> 98  
98 -> 99  
99 -> 100  
100 -> 100  
```

**Comment by jewzaam** [comment]
GradualActivationStrategy gets the percentage with `user.getName().hashCode() % 100`.  With such a small set of user names generated by us and use of hash code distribution cannot be good.  I have a unit test that shows this though it doesn't match what you see.  By increasing the number of user names generated we get much better distribution.

**Comment by paterczm** [comment]
Build is failing.
