### ISSUE TITLE
When there is a mismatch between elements of an array, entire array element is logged as diff

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-migrator#287]
This makes it impossible to tell which fields are different at a glance. You need to save both elements' json representations to disk and compare with diff. This is inefficient, the diff printed in inconsistency log should be as small as possible.

**Comment by paterczm** [comment]
This is low priority, since we're using @ykoer's ldiff tool to generate nice diffs.

**Comment by bserdar** [comment]
There's a new JsonComparator in core/util package. We can start using that
in the logs
