### ISSUE TITLE
Configuration values should be configurable externally

### ISSUE THREAD

**Issue by BVulaj** [lightblue-platform/lightblue-migrator#290]
There are some config fields that are hardcoded which should be configurable on the fly.
For example:

    private int timeoutSeconds = 5;

In lieu of a DI framework, we should be using something like [Apache Commons Config](https://commons.apache.org/proper/commons-configuration/)

The ACC allows you to set some preferred defaults (or not), while allowing others to override those defaults via a number of means.  Properties files, XML, system props, env vars, JNDI, etc.

There are also listeners built in, which would allow the services to not require a restart when these values are changed.

This project is a decent testing ground, but I'd argue we should implement this throughout LB once we're comfortable with it.

**Comment by paterczm** [comment]
This is resolved by https://github.com/lightblue-platform/lightblue-migrator/pull/288. I don't think we have any hardcoded configurations right now. Closing this issue.
