### ISSUE TITLE
DAO proxying (vs. whole service proxying)?

### ISSUE THREAD

**Issue by kahowell** [lightblue-platform/lightblue-migrator#306]
If I understand correctly, the preferred strategy right now is to proxy an entire service, rather than just the DAO. The documentation (esp. unit tests and README) refer to DAO only.

**Comment by paterczm** [comment]
I will leave the unit tests as is, but clarified this in the documentation: https://github.com/lightblue-platform/lightblue-migrator/commit/fa42ced0588b27f32d9ec7f6f08d16a38e4fc335
