### ISSUE TITLE
Using both ReadOperation and WriteOperation on the same method can cause bugs

### ISSUE THREAD

**Issue by kahowell** [lightblue-platform/lightblue-migrator#307]
In perusing the code, I noticed that `FacadeInvocationHandler.invoke` will invoke the methods twice if both annotations are present (if I read correctly). See https://github.com/lightblue-platform/lightblue-migrator/blob/master/facade/src/main/java/com/redhat/lightblue/migrator/facade/proxy/FacadeProxyFactory.java#L85. I think proper behavior might be to throw an exception if both are present.

Maybe this is accounted for elsewhere, but even if it is, I'd feel better about it if the method was an if-else-if, rather than just if-if...

**Comment by paterczm** [comment]
The invoke method will return on the first match, so it will not execute svc method twice..

**Comment by kahowell** [comment]
:+1: Thanks for clarifying. Did not notice the `return`.
