### ISSUE TITLE
Use lightblue-client-integration-test from lightblue-client 4.2.0-SNAPSHOT (java8)

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-migrator#327]
This requires migrator tests to be run on java8 only. Everything else should be built using java7. Lightblue-core-util can be removed from the project.

@dcrissman, can you take this one?

**Comment by dcrissman** [comment]
The java8 issues were fixed in https://github.com/lightblue-platform/lightblue-migrator/pull/324, bumping deps to see if there are any issues or not in #328.
