### ISSUE TITLE
Add configurability to how many times the daemon would attempt to restart the Migrator thread.

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#40]
This is a spin off of #38 38. Some of the logic has already been roughed in, but in the spirit of getting a merge accepted, we decided to break out into its own feature.

The desire is that a optional configuration option can be passed into the daemon stating how many time it would attempt to restart the worker thread before exiting out altogether. It should support -1 for infinite retries (default), 0 for don't retry at all, or an int specifying the max number of retries. All events should be logged.

**Comment by jewzaam** [comment]
Could be a hard throttle or maybe a delayed restart after some number of failures?

**Comment by bserdar** [comment]
No longer relevant
