### ISSUE TITLE
Change feature flag implementation to support multiple feature flag configs per deployment

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-migrator#54]
Currently the use of Toggle uses their default static feature configuration.  Update our wrapper around this to support the use of multiple configurations for the same feature flags so that single deployments can re-use feature flags in multiple modules.

**Comment by jewzaam** [comment]
Is this a thing for migrator or should it be somewhere else?

**Comment by derek63** [comment]
It belongs in the migrator I think since the feature flag stuff is referenced by the core module (and used by migrated/proxied services)

**Comment by paterczm** [comment]
This can be done as part of https://github.com/lightblue-platform/lightblue-migrator/issues/174.

**Comment by jewzaam** [comment]
Closing in favor of issue with specific solution noted by Marek, #174
