### ISSUE TITLE
MigrationJob does not appear to iterate over items in sub-arrays for consistency comparisons

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#65]
The migrator seems to be attempting to compare entire arrays, instead of each individual element. I suspect we would want ways to exclude elements in sub-arrays/objects just like top level elements.

The other question this brings to mind is does it handle sub-objects in the same way?

-
source:
> [{"statusCode":"active","termsVerbiageTranslation":[{"statusCode":"active","localeCodeText":"en_US","publishedFlag":true,"url":" "}],"versionText":"1","description":"Evaluation Terms"}]

-
destination:
> [{"statusCode":"active","uid":"bd70bd99-b443-4ce2-bd02-f87c772a6513","termsVerbiageTranslation":[{"uid":"c65d6f5e-ffdd-4bba-940c-fea307790bfa","localeCodeText":"en_US","publishedFlag":true,"url":" ","statusCode":"active","creationDate":"20150216T18:07:27.880+0000"}],"versionText":"1","description":"Evaluation Terms","name":"someName","termsVerbiageTranslation#":1}]

**Comment by jewzaam** [comment]
Can the destination query be setup with a projection?  If so, then use projection to exclude fields you don't want to compare.  Or build that projection from the field exclusion list?

**Comment by dcrissman** [comment]
It doesn't appear that the Migrator currently depends on lightblue-core, I am not sure if that was a design decision or not, but is at least one change that would need to be made if we go down that path.

**Comment by jewzaam** [comment]
Why?  The query should have the projection in the request.

**Comment by dcrissman** [comment]
I see what you mean, but I don't know that would totally solve the issue. It would certainly filter out fields we don't care about, but we still need to iterate over the individual array/object values to ensure they match.

**Comment by dcrissman** [comment]
The other potential issue I see is that the migrator has the idea of excluded fields, but seemingly only on the top level element. So we might need to change it to support Path like notations for Projections or comparisons.

**Comment by jewzaam** [comment]
Comparison could rely on order of elements, which are kept in mongo.  So if it is ordered consistently by migrator from the source it will be consistent in the destination.  And if they're different it needs overwritten.

One issue will be if there are fields in the destination that were not represented in the source.  I don't think that should be allowed so your example above may not be valid with the exception of generated fields, which today are only fields with type uid and _id for mongo backend.  Uid fields could be set on migration from the source, they don't have to be generated.

**Comment by jewzaam** [comment]
Ah, one other exception is the array count field.  Those could be excluded from the projection.

**Comment by dcrissman** [comment]
> Ah, one other exception is the array count field. Those could be excluded from the projection.

We would need to take into account a field that happens to end with a '#'. So blindly ignoring all such fields wouldn't work.

**Comment by jewzaam** [comment]
Track that as a separate issue and solve it later.  It's not something we need to be worried with right now.  Are we going to create any metadata with # in the field name?
