### ISSUE TITLE
Need to rotate log file

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#83]

**Comment by jewzaam** [comment]
How are logs managed today?  If it's a common logging framework it should be a simple matter to configure log retention.

**Comment by dcrissman** [comment]
@jewzaam We are using log4j under the hood, which provides RollingFileAppender for just this sort of thing.

This will be handled in https://github.com/lightblue-platform/lightblue-puppet/issues/121
