### ISSUE TITLE
Unable to process job when projection isn't returned

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#94]
```
2015-03-11 10:23:35,493 [pool-1-thread-1] com.redhat.lightblue.migrator.consistency.MigrationJob ERROR - Error while processing job termsAcknowledgementJob_4703 with MigrationConfiguration [configFilePath=/usr/share/migrator/lightblue-client.properties, migrationConfigurationEntityVersion=null, migrationJobEntityVersion=0.1.0-SNAPSHOT, authorizedHostnames=[lightbluehystrix1.dev.a1.vary.redhat.com, lightbluehystrix2.dev.a1.vary.redhat.com], threadCount=1, configurationName=termsAcknowledgement, consistencyCheckerName=hystrix, comparisonExclusionPaths=[acknowledgedDate], destinationEntityName=termsAcknowledgementJDBC, destinationEntityVersion=1.0.1, destinationIdentityFields=[_id], sourceEntityName=termsAcknowledgementOracle, sourceEntityVersion=1.0.1, sourceTimestampPath=acknowledgedDate, overwriteDestinationDocuments=true] for start date 20060716T04:00:00.000+0000 and end date 20060716T05:00:00.000+0000
java.lang.RuntimeException: Error parsing lightblue response: {"status":"COMPLETE","modifiedCount":1,"matchCount":0}
	at com.redhat.lightblue.migrator.consistency.MigrationJob.shouldProcessJob(MigrationJob.java:373)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.run(MigrationJob.java:279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.redhat.lightblue.migrator.consistency.MigrationJob[] out of NOT_AVAILABLE token
 at [Source: N/A; line: -1, column: -1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:569)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:135)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.redhat.lightblue.migrator.consistency.MigrationJob.shouldProcessJob(MigrationJob.java:338)
	... 4 more

```

**Comment by jewzaam** [comment]
That's interesting given:
1. the migrationJob already exists
2. the update to append to jobExecutions projects * recursively

The response is quirky: `{"status":"COMPLETE","modifiedCount":1,"matchCount":0}`
How can it modify 1 record but nothing matched?

**Comment by jewzaam** [comment]
@bserdar any ideas?

**Comment by bserdar** [comment]
matchCount is only meaningful for retrieval, not update/insert.

**Comment by bserdar** [comment]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can
not deserialize instance of
com.redhat.lightblue.migrator.consistency.MigrationJob[] out of
NOT_AVAILABLE token

Is it trying to parse an empty string to get a MigrationJob?

**Comment by jewzaam** [comment]
I think the json response is `{"status":"COMPLETE","modifiedCount":1,"matchCount":0}`.
@dcrissman do you have the json request?

**Comment by dcrissman** [comment]
@jewzaam what you have above is correct.

**Comment by jewzaam** [comment]
@dcrissman and the request?

**Comment by dcrissman** [comment]
@jewzaam sorry, misread your earlier question. Here is an example of a request.

```json
{"query":{"field":"_id","op":"=","rvalue":"__censored__"},"update":[{"$append":{"jobExecutions":{}}},{"$set":{"jobExecutions.-1.ownerName":"hystrix"}},{"$set":{"jobExecutions.-1.hostName":"$(hostname)"}},{"$set":{"jobExecutions.-1.pid":"30730@localhost.localdomain"}},{"$set":{"jobExecutions.-1.actualStartDate":"20150311T17:28:25.750+0000"}},{"$set":{"jobExecutions.-1.actualEndDate":"$null"}},{"$set":{"jobExecutions.-1.completedFlag":false}},{"$set":{"jobExecutions.-1.processedDocumentCount":0}},{"$set":{"jobExecutions.-1.consistentDocumentCount":0}},{"$set":{"jobExecutions.-1.inconsistentDocumentCount":0}},{"$set":{"jobExecutions.-1.overwrittenDocumentCount":0}}],"projection":[{"field":"*","include":true,"recursive":true}]}
```

**Comment by bserdar** [comment]
So, I see two problems:
 1)
JsonNode node = response.getJson().path("processed");  try {  MigrationJob[]
jobs = mapper.readValue(node.traverse(), MigrationJob[].class);
Add a null check here

2) The real problem: why is it not returning anything? Can you check the
logs? Maybe there's an error somewhere, but we're not propagaring properly?

**Comment by dcrissman** [comment]
Seems intermittent when run locally.

Worked: entity_6732

Failed: entity_6807
```json
{"query":{"field":"_id","op":"=","rvalue":"entity_6807"},"update":[{"$append":{"jobExecutions":{}}},{"$set":{"jobExecutions.-1.ownerName":"hystrix"}},{"$set":{"jobExecutions.-1.hostName":"$(hostname)"}},{"$set":{"jobExecutions.-1.pid":"1780@localhost.localdomain"}},{"$set":{"jobExecutions.-1.actualStartDate":"20150311T18:50:39.496+0000"}},{"$set":{"jobExecutions.-1.actualEndDate":"$null"}},{"$set":{"jobExecutions.-1.completedFlag":false}},{"$set":{"jobExecutions.-1.processedDocumentCount":0}},{"$set":{"jobExecutions.-1.consistentDocumentCount":0}},{"$set":{"jobExecutions.-1.inconsistentDocumentCount":0}},{"$set":{"jobExecutions.-1.overwrittenDocumentCount":0}}],"projection":[{"field":"*","include":true,"recursive":true}]}
```
```json
{"status":"COMPLETE","modifiedCount":1,"matchCount":0}
```

**Comment by dcrissman** [comment]
> 2) The real problem: why is it not returning anything? Can you check the logs? Maybe there's an error somewhere, but we're not propagaring properly?

@bserdar I do not see any errors that directly correlate.

**Comment by bserdar** [comment]
Can you reproduce it? Is there a record where it consistently fails?

**Comment by dcrissman** [comment]
> Worked: entity_6732
> Failed: entity_6807

I manually ran the update above using curl. The first time it worked for both, but then all subsequent runs fail in the sense that no processed results are returned AND no additional jobExecutions are appended to the array. It makes me think there is something wrong with the update, except that doesn't explain why entity_6807 did not work earlier, but then worked manually once only to fail from then on.

**Comment by bserdar** [comment]
Can you get that record from the db, and the metadata, and write a unit
test under mongo module for it that updates it using the same update
expression you have?

**Comment by dcrissman** [comment]
There are actually zero records in the db for the time frame represented by both jobs.

I will see what I can do about a unit test.

**Comment by dcrissman** [comment]
It has something to do with this...
```json
{"$set":{"jobExecutions.-1.actualEndDate":"$null"}}
```
If I set the actualEndDate to an actual value, then everything seems to work just fine.

The entity says that the actualEndDate is required:
```json
"actualEndDate": {
    "type": "date",
    "constraints": {
        "required": true
    },
    "description": "Actual end date for this migration job"
}
```
This being the case, it would seem like the expected behaviour would be to get an error message back.

**Comment by jewzaam** [comment]
I recommend removing the constraint from actualEndDate

**Comment by bserdar** [comment]
So the working hypothesis is:
   - Update operation sets actualEndDate to null
   - Constraint violation fails
   - Somehow that failure information is lost

I'll write a unit test to test this.

**Comment by bserdar** [comment]
It looks like setting something to $null doesn't violate the 'required'
constraint, becuse the field exists, and 'required' checks the field
existence.

Did you have a change to test this without the constraint?

**Comment by bserdar** [comment]
Pushed a minor fix to updater, but everything seems to be running as
expected. I don't think this is related to constraint validations.

Could this be a race condition? Are you running multiple instances of the
migrator?

**Comment by dcrissman** [comment]
> Did you have a change to test this without the constraint?

Yes, sadly problem continues.

> Could this be a race condition? Are you running multiple instances of the migrator?

I had thought this too, but I am able to produce with only a single migrator running.

**Comment by jewzaam** [comment]
There are multiple threads running in the single migrator or one thread?

----- Original Message -----

**Comment by dcrissman** [comment]
> There are multiple threads running in the single migrator or one thread?

Number of threads allowed is configured per job, and both jobs are set to only use 1 thread. So a total of two threads, but each working on different entities.

**Comment by bserdar** [comment]
Is the entity updated correctly, even though the projected result is empty?

**Comment by dcrissman** [comment]
> Is the entity updated correctly, even though the projected result is empty?

I am able to consistently reproduce for entity_6264 (db has 0 records for this dataset), the before and after jobExecutions values of two runs are unchanged. Regardless of how many times I run the migrator over this job, no additional jobExecutions are added and the existing result is unchanged.

```json
            "jobExecutions": [
                {
                    "actualStartDate": "20150312T13:26:41.943+0000", 
                    "completedFlag": false, 
                    "consistentDocumentCount": 0, 
                    "hostName": "myhost", 
                    "inconsistentDocumentCount": 0, 
                    "overwrittenDocumentCount": 0, 
                    "ownerName": "theman", 
                    "pid": "18161@myhost", 
                    "processedDocumentCount": 0
                }
            ]
```

**Comment by bserdar** [comment]
Wrote a unit test, and it is updating as expected.

Can you set the server loglevel to DEBUG, and then run this update and get
the full log?

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/pull/345
https://github.com/lightblue-platform/lightblue-mongo/pull/83

Please merge these two, deploy, and test again. After this, it should at
least return the error.

**Comment by bserdar** [comment]
It is complaining about the 0'th element of the array:

{"status":"PARTIAL","modifiedCount":0,"matchCount":0,"dataErrors":[{"data":{"creationDate":"20150305T15:31:57.000+0000","expectedExecutionMilliseconds":30000,"startDate":"20060629T02:00:00.000+0000","createdBy":"dcrissma","_id":"termsAcknowledgementJob_4293","lastUpdatedBy":"dcrissma","jobExecutions":[{"ownerName":"hystrix","consistentDocumentCount":0,"completedFlag":false,"overwrittenDocumentCount":0,"actualStartDate":"20150312T17:25:58.478+0000","hostName":"
lightbluehystrix2.dev.a1.vary.redhat.com","pid":"
24354@lightbluehystrix2.dev.a1.vary.redhat.com
","inconsistentDocumentCount":0,"processedDocumentCount":0},{"ownerName":"hystrix","hostName":"$(hostname)","pid":"18299@localhost.localdomain
","actualStartDate":"20150313T18:25:09.443+0000","actualEndDate":null,"completedFlag":false,"processedDocumentCount":0,"consistentDocumentCount":0,"inconsistentDocumentCount":0,"overwrittenDocumentCount":0}],"endDate":"20060629T03:00:00.000+0000","whenAvailableDate":"20150305T05:00:00.000+0000","configurationName":"termsAcknowledgement","objectType":"migrationJob","lastUpdateDate":"20150305T15:31:57.000+0000","jobExecutions#":2},"errors":[{"objectType":"error","context":"rest/UpdateCommand/migrationJob/update(migrationJob:0.1.0-SNAPSHOT)/update/validateDoc/jobExecutions.*.actualEndDate/required","errorCode":"crud:Required","msg":"jobExecutions.0.actualEndDate"}]}]}

**Comment by dcrissman** [comment]
The root issue was that the end date field was still being required, a configuration change fixed this.
