### ISSUE TITLE
Make Hystrix optional in the migrator

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#96]
Spin-off of https://github.com/lightblue-platform/lightblue-migrator/pull/95

**Comment by jewzaam** [comment]
Why bother making it optional?

**Comment by dcrissman** [comment]
My thinking was that we make hystrix optional for crud and metadata, so I wanted us to be consistent. That said and upon further review, we make this optional in the ServoGraphiteSetup which is now shared amongst all 3. So hystrix can simply be turned off by not including the environment variables.

I will close this ticket.
