### ISSUE TITLE
Migrator does not seem to be picking up the STATSD env vars.

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-migrator#99]
> 2015-03-13 11:11:10,540 [ConsistencyCheckerRunner] com.redhat.lightblue.hystrix.ServoGraphiteSetup INFO - StatdsMetricObserver not configured, missing environment variable: STATSD_HOSTNAME

-

> cat /etc/profile.d/lb-statsd.sh 
> #This file is managed by Puppet, any changes will be overridden.
>
> export STATSD_PREFIX=lightblue
> export STATSD_HOSTNAME=localhost
> export STATSD_PORT=8125

-

> \# echo $STATSD_HOSTNAME
> localhost
> \# echo $STATSD_PREFIX
> lightblue
> \# echo $STATSD_PORT
> 8125

**Comment by jewzaam** [comment]
Is it maybe a problem with env variables not propagating via jsvc?

**Comment by dcrissman** [comment]
Fixes elsewhere. See:
* https://github.com/lightblue-platform/lightblue-puppet/pull/120
* https://github.com/lightblue-platform/lightblue-core/pull/348
